### ISSUE TITLE
July 26th 2023

### ISSUE THREAD

**Issue by briandepasquale** [rsenne/PulseInputDDM#1]
- Take a look at PulseInputDDM.jl (super high front end), base_model.jl (more important stuff for different types of models), choice_model.jl (choice model specific stuff), examples/choice_model.ipynb is a overall walkthrough of the data generation and modeling fitting.

- Things to maybe think about at some point....
- Lobotomized both codebases (e.g. remove adaptation from Brian's code, and collapsing bounds from Gary's)

**Comment by briandepasquale** [comment]
- New issue: look at `load_choice_data` in `\choice_model\process_data.jl` and make a new helper function that does pretty much the same thing, but for R files.

**Comment by briandepasquale** [comment]
- Use \sigma_i = 1e-3, lapse = 0 , bias = 0, \sigma_s = 1e-3, \phi = 1, \tau_phi = 1e-3, to lobotmize the model so we are only fitting \sigma_a, B and \lambda.
- Ask Gary about why he's not using lapse rate.

**Comment by rsenne** [comment]
above have been addressed/and or completed to best of ability. closing issue for record keeping sake, as new goals arise, new issues can be created :)
